/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fixent.rm.client.view;

/**
 *
 * @author Mathan
 */
public class MaintenanceView extends javax.swing.JPanel {

    /**
     * Creates new form RentMaintenanceView
     */
    public MaintenanceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShopTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        groupAddButton = new javax.swing.JButton();
        groupDeleteButton = new javax.swing.JButton();
        shopAddButton = new javax.swing.JButton();
        shopDeleteButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Group");

        ShopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ShopTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(ShopTable);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Shop");

        groupAddButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        groupAddButton.setText("Add");

        groupDeleteButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        groupDeleteButton.setText("Delete");

        shopAddButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        shopAddButton.setText("Add");

        shopDeleteButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        shopDeleteButton.setText("Delete");

        groupTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        groupTable.setFillsViewportHeight(true);
        jScrollPane3.setViewportView(groupTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shopAddButton)
                        .addGap(10, 10, 10)
                        .addComponent(shopDeleteButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(groupAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(groupDeleteButton))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupAddButton)
                    .addComponent(groupDeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shopAddButton)
                    .addComponent(shopDeleteButton))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ShopTable;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton groupAddButton;
    private javax.swing.JButton groupDeleteButton;
    private javax.swing.JTable groupTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton shopAddButton;
    private javax.swing.JButton shopDeleteButton;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JTable getShopTable() {
		return ShopTable;
	}

	public void setShopTable(javax.swing.JTable shopTable) {
		ShopTable = shopTable;
	}

	public javax.swing.JButton getGroupAddButton() {
		return groupAddButton;
	}

	public void setGroupAddButton(javax.swing.JButton groupAddButton) {
		this.groupAddButton = groupAddButton;
	}

	public javax.swing.JButton getGroupDeleteButton() {
		return groupDeleteButton;
	}

	public void setGroupDeleteButton(javax.swing.JButton groupDeleteButton) {
		this.groupDeleteButton = groupDeleteButton;
	}

	public javax.swing.JTable getGroupTable() {
		return groupTable;
	}

	public void setGroupTable(javax.swing.JTable groupTable) {
		this.groupTable = groupTable;
	}

	public javax.swing.JLabel getjLabel1() {
		return jLabel1;
	}

	public void setjLabel1(javax.swing.JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	public javax.swing.JLabel getjLabel2() {
		return jLabel2;
	}

	public void setjLabel2(javax.swing.JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}

	public javax.swing.JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	public javax.swing.JScrollPane getjScrollPane3() {
		return jScrollPane3;
	}

	public void setjScrollPane3(javax.swing.JScrollPane jScrollPane3) {
		this.jScrollPane3 = jScrollPane3;
	}

	public javax.swing.JButton getShopAddButton() {
		return shopAddButton;
	}

	public void setShopAddButton(javax.swing.JButton shopAddButton) {
		this.shopAddButton = shopAddButton;
	}

	public javax.swing.JButton getShopDeleteButton() {
		return shopDeleteButton;
	}

	public void setShopDeleteButton(javax.swing.JButton shopDeleteButton) {
		this.shopDeleteButton = shopDeleteButton;
	}
    
}
